# Generated by Django 4.1.5 on 2023-04-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='fullname of the user', max_length=30),
        ),
    ]
