# Generated by Django 4.1.7 on 2023-05-10 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.user')),
                ('captcha_1', models.CharField(max_length=50)),
                ('captcha_2', models.CharField(max_length=50)),
                ('captcha_3', models.CharField(max_length=50)),
                ('captcha_4', models.CharField(max_length=50)),
                ('captcha_5', models.CharField(max_length=50)),
                ('captcha_6', models.CharField(max_length=50)),
                ('captcha_7', models.CharField(max_length=50)),
                ('captcha_8', models.CharField(max_length=50)),
            ],
        ),
    ]
